import numpy as np

BOARD_SIZE = 9
STARTING_BUTTONS = 5
MAP_LENGTH = 54
MAX_FABRICS = 5
BONUS_ARRAY = np.zeros((7, 7))+1

BUTTONS = [5, 11, 17, 23, 29, 35, 41, 47, 53]
BUTTONS_PLACEMENT = [0]*MAP_LENGTH

for button in BUTTONS:
    BUTTONS_PLACEMENT[button] = 1

SINGLE_FABRIC = [26, 32, 38, 44, 50]
SINGLE_FABRIC_PLACEMENT = [0]*MAP_LENGTH

for fabric in SINGLE_FABRIC:
    SINGLE_FABRIC_PLACEMENT[fabric] = 1
